/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author labuc9806
 */
public class multiplequizfrm extends javax.swing.JFrame {

    int totalCorrect = 0;
    int totalIncorrect = 0;
    int userGuess;
    int userGuess2;
    int userGuess3;
    int userGuess4;
    int userGuess5;
    int percCorrect;
    /**
     * Creates new form multiplequizfrm
     */
    public multiplequizfrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        q1lbl = new javax.swing.JLabel();
        q2lbl = new javax.swing.JLabel();
        q3lbl = new javax.swing.JLabel();
        q4lbl = new javax.swing.JLabel();
        q5lbl = new javax.swing.JLabel();
        ansinputlbl = new javax.swing.JLabel();
        ansinputlbl2 = new javax.swing.JLabel();
        ansinputlbl3 = new javax.swing.JLabel();
        ansinputlbl4 = new javax.swing.JLabel();
        ansinputlbl5 = new javax.swing.JLabel();
        a1lbl = new javax.swing.JLabel();
        b1lbl = new javax.swing.JLabel();
        c1lbl = new javax.swing.JLabel();
        d1lbl = new javax.swing.JLabel();
        ans1txt = new javax.swing.JTextField();
        a2lbl = new javax.swing.JLabel();
        b2lbl = new javax.swing.JLabel();
        c2lbl = new javax.swing.JLabel();
        d2lbl = new javax.swing.JLabel();
        ans2txt = new javax.swing.JTextField();
        a3lbl = new javax.swing.JLabel();
        b3lbl = new javax.swing.JLabel();
        c3lbl = new javax.swing.JLabel();
        d3lbl = new javax.swing.JLabel();
        ans3txt = new javax.swing.JTextField();
        q4lbl2 = new javax.swing.JLabel();
        a4lbl = new javax.swing.JLabel();
        b4lbl = new javax.swing.JLabel();
        ans4txt = new javax.swing.JTextField();
        q5lbl2 = new javax.swing.JLabel();
        a5lbl = new javax.swing.JLabel();
        b5lbl = new javax.swing.JLabel();
        c5lbl = new javax.swing.JLabel();
        ans5txt = new javax.swing.JTextField();
        calbtn = new javax.swing.JButton();
        correctlbl = new javax.swing.JLabel();
        incorrectlbl = new javax.swing.JLabel();
        perclbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        q1lbl.setText("Question 1 : An interpreter does everything except... ");

        q2lbl.setText("Question 2 : The number -98.556 can be stored as a :");

        q3lbl.setText("Question 3 : What source package must you add in order to create a GUI?");

        q4lbl.setText("Question 4 : int number 1 = 5; int number2 = 32; int number3 = 16; ");

        q5lbl.setText("Question 5 : What does the following line of code do? ");

        ansinputlbl.setText("Answer: ");

        ansinputlbl2.setText("Answer:");

        ansinputlbl3.setText("Answer:");

        ansinputlbl4.setText("Answer :");

        ansinputlbl5.setText("Answer :");

        a1lbl.setText("1. Translate program one line at a time");

        b1lbl.setText("2. Generates an error message after scanning the entire program ");

        c1lbl.setText("3.Is used by programming languages like Python and Ruby");

        d1lbl.setText("4. Takes less time to analyze source code");

        ans1txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans1txtActionPerformed(evt);
            }
        });

        a2lbl.setText("1. Integer");

        b2lbl.setText("2. String ");

        c2lbl.setText("3. Boolean");

        d2lbl.setText("4. Double");

        ans2txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans2txtActionPerformed(evt);
            }
        });

        a3lbl.setText("1. Java Interface");

        b3lbl.setText("2. Java Panel Form");

        c3lbl.setText("3. Java Frame Form");

        d3lbl.setText("4. Java Class");

        ans3txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans3txtActionPerformed(evt);
            }
        });

        q4lbl2.setText(" number1 != number2 ");

        a4lbl.setText("1. True ");

        b4lbl.setText("2. False");

        ans4txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans4txtActionPerformed(evt);
            }
        });

        q5lbl2.setText("percCorrect = ((double)totalCorrect/(double)totalRolls)*100;");

        a5lbl.setText("1. Rounds the number to two decimal places");

        b5lbl.setText("2. Doubles the value of both variables");

        c5lbl.setText("3. Tells Java to treat the variables as doubles ");

        ans5txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans5txtActionPerformed(evt);
            }
        });

        calbtn.setText("Calculate Results");
        calbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Correct:");

        jLabel2.setText("Incorrect :");

        jLabel3.setText("Percentage :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b5lbl)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(q4lbl)
                                .addGap(18, 18, 18)
                                .addComponent(ansinputlbl4))
                            .addComponent(a5lbl)
                            .addComponent(c5lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calbtn)
                            .addComponent(ans4txt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(perclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(correctlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(incorrectlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(q5lbl2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(a4lbl)
                            .addComponent(b4lbl)
                            .addComponent(b1lbl)
                            .addComponent(c1lbl)
                            .addComponent(a1lbl)
                            .addComponent(d1lbl)
                            .addComponent(a2lbl)
                            .addComponent(c2lbl)
                            .addComponent(d2lbl)
                            .addComponent(b2lbl)
                            .addComponent(a3lbl)
                            .addComponent(c3lbl)
                            .addComponent(d3lbl)
                            .addComponent(b3lbl)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(q1lbl)
                                .addGap(18, 18, 18)
                                .addComponent(ansinputlbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ans1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(q3lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ansinputlbl3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ans3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(q2lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ansinputlbl2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ans2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(q5lbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(ansinputlbl5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ans5txt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(q4lbl2))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addGap(6, 6, 6)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(328, 328, 328)
                                .addComponent(jLabel3)))))
                .addGap(31, 31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1lbl)
                    .addComponent(ansinputlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ans1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(a1lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b1lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c1lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(d1lbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2lbl)
                    .addComponent(ansinputlbl2)
                    .addComponent(ans2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(a2lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b2lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c2lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(d2lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3lbl)
                    .addComponent(ansinputlbl3)
                    .addComponent(ans3txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(a3lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b3lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c3lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d3lbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q4lbl)
                    .addComponent(ansinputlbl4)
                    .addComponent(ans4txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q4lbl2)
                .addGap(11, 11, 11)
                .addComponent(a4lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b4lbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q5lbl)
                    .addComponent(ans5txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ansinputlbl5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(q5lbl2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a5lbl)
                        .addGap(11, 11, 11)
                        .addComponent(b5lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c5lbl))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(calbtn)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(incorrectlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(correctlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(perclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ans1txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans1txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans1txtActionPerformed

    private void ans2txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans2txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans2txtActionPerformed

    private void ans3txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans3txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans3txtActionPerformed

    private void ans4txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans4txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans4txtActionPerformed

    private void ans5txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans5txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans5txtActionPerformed

    private void calbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calbtnActionPerformed

        

        userGuess = Integer.parseInt (ans1txt.getText());
       
        
        if (userGuess == 2)
        { 
            totalCorrect = totalCorrect +1;
                }     
        else
        {
            totalIncorrect = totalIncorrect +1;
        }
        
        userGuess2 = Integer.parseInt (ans2txt.getText());
        
        if (userGuess2 == 4)
        {
            totalCorrect = totalCorrect +1;
        }
        else 
        {
            totalIncorrect = totalIncorrect +1;
        }
        
        userGuess3 = Integer.parseInt (ans3txt.getText());
        
        if (userGuess3 == 3)
        {
            totalCorrect = totalCorrect +1;
        }
        else
        {
            totalIncorrect = totalIncorrect +1;
        }
        
        userGuess4 = Integer.parseInt (ans4txt.getText());
        
        if (userGuess4 == 1)
        {
            totalCorrect = totalCorrect +1;
        }
        else
        {
            totalIncorrect = totalIncorrect +1;
        }
        
        userGuess5 = Integer.parseInt (ans5txt.getText());
        
        if (userGuess5 == 3)
        {
            totalCorrect = totalCorrect +1;
        }
        else
        { totalIncorrect = totalIncorrect +1;
        
        }
        
        percCorrect = (int) (((double)totalCorrect/(double)5)*100);
        percCorrect = percCorrect *100;
        percCorrect = Math.round(percCorrect);
        percCorrect = percCorrect/100;
        
        correctlbl.setText(String.valueOf("+totalCorrect+"));
        incorrectlbl.setText(String.valueOf("+totalIncorrect+"));
        perclbl.setText (String.valueOf("+percCorrect+"));
            
        
      
            
                

    }//GEN-LAST:event_calbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(multiplequizfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(multiplequizfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(multiplequizfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(multiplequizfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new multiplequizfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1lbl;
    private javax.swing.JLabel a2lbl;
    private javax.swing.JLabel a3lbl;
    private javax.swing.JLabel a4lbl;
    private javax.swing.JLabel a5lbl;
    private javax.swing.JTextField ans1txt;
    private javax.swing.JTextField ans2txt;
    private javax.swing.JTextField ans3txt;
    private javax.swing.JTextField ans4txt;
    private javax.swing.JTextField ans5txt;
    private javax.swing.JLabel ansinputlbl;
    private javax.swing.JLabel ansinputlbl2;
    private javax.swing.JLabel ansinputlbl3;
    private javax.swing.JLabel ansinputlbl4;
    private javax.swing.JLabel ansinputlbl5;
    private javax.swing.JLabel b1lbl;
    private javax.swing.JLabel b2lbl;
    private javax.swing.JLabel b3lbl;
    private javax.swing.JLabel b4lbl;
    private javax.swing.JLabel b5lbl;
    private javax.swing.JLabel c1lbl;
    private javax.swing.JLabel c2lbl;
    private javax.swing.JLabel c3lbl;
    private javax.swing.JLabel c5lbl;
    private javax.swing.JButton calbtn;
    private javax.swing.JLabel correctlbl;
    private javax.swing.JLabel d1lbl;
    private javax.swing.JLabel d2lbl;
    private javax.swing.JLabel d3lbl;
    private javax.swing.JLabel incorrectlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel perclbl;
    private javax.swing.JLabel q1lbl;
    private javax.swing.JLabel q2lbl;
    private javax.swing.JLabel q3lbl;
    private javax.swing.JLabel q4lbl;
    private javax.swing.JLabel q4lbl2;
    private javax.swing.JLabel q5lbl;
    private javax.swing.JLabel q5lbl2;
    // End of variables declaration//GEN-END:variables
}
